---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  require_chef_omnibus: 11
  client_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: centos-6.7

suites:
  - name: default
    data_bags_path: ./test/fixtures/data_bags
    encrypted_data_bag_secret_key_path: ./test/fixtures/data_bags/encrypted_data_bag_secret
    run_list:
      - flyway_percona_test::default
    attributes:
