-- MySQL Script generated by MySQL Workbench
-- 02/12/16 10:04:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema example
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `example` ;

-- -----------------------------------------------------
-- Schema example
-- -----------------------------------------------------
#CREATE SCHEMA IF NOT EXISTS `example` DEFAULT CHARACTER SET utf8 ;
#USE `example` ;

-- -----------------------------------------------------
-- Table `example`.`accomodationlookup`
-- -----------------------------------------------------
#DROP TABLE IF EXISTS `example`.`accomodationlookup` ;

CREATE TABLE IF NOT EXISTS `example`.`accomodationlookup` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdBy_id` BIGINT(20) NULL DEFAULT NULL,
  `createdBy_name` VARCHAR(255) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `modifiedBy_id` BIGINT(20) NULL DEFAULT NULL,
  `modifiedBy_name` VARCHAR(255) NULL DEFAULT NULL,
  `modifiedDate` DATETIME NULL DEFAULT NULL,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `identifier` VARCHAR(255) NULL DEFAULT NULL,
  `incompatible` VARCHAR(255) NULL DEFAULT NULL,
  `mode` VARCHAR(255) NULL DEFAULT NULL,
  `mustHaveAllIds` VARCHAR(255) NULL DEFAULT NULL,
  `mustHaveOnlyOneIds` VARCHAR(255) NULL DEFAULT NULL,
  `subTitle` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `semiCompatible` VARCHAR(255) NULL DEFAULT NULL,
  `displayOrder` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 39
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `example`.`accomodationsubjectlookup`
-- -----------------------------------------------------
#DROP TABLE IF EXISTS `example`.`accomodationsubjectlookup` ;

CREATE TABLE IF NOT EXISTS `example`.`accomodationsubjectlookup` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createdBy_id` BIGINT(20) NULL DEFAULT NULL,
  `createdBy_name` VARCHAR(255) NULL DEFAULT NULL,
  `createdDate` DATETIME NULL DEFAULT NULL,
  `modifiedBy_id` BIGINT(20) NULL DEFAULT NULL,
  `modifiedBy_name` VARCHAR(255) NULL DEFAULT NULL,
  `modifiedDate` DATETIME NULL DEFAULT NULL,
  `incompatible` VARCHAR(255) NULL DEFAULT NULL,
  `mustHaveAllIds` VARCHAR(255) NULL DEFAULT NULL,
  `mustHaveOneId` VARCHAR(255) NULL DEFAULT NULL,
  `subject` VARCHAR(255) NULL DEFAULT NULL,
  `accomodationLookup_id` BIGINT(20) NULL DEFAULT NULL,
  `subjectOrder` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKE76E2BE585F19CF7`
  FOREIGN KEY (`accomodationLookup_id`)
  REFERENCES `example`.`accomodationlookup` (`id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 75
  DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FKE76E2BE585F19CF7` ON `example`.`accomodationsubjectlookup` (`accomodationLookup_id` ASC);
